/*
* Proyecto1_Reloj.asm
*
* Creado: 2/24/2026 7:12:15 PM
* Autor : Andrés Barrientos
* Descripción: Reloj (Proyecto 1)
*/
/****************************************/
// Encabezado (Definición de Registros, Variables y Constantes)
.include "M328PDEF.inc"     // Include definitions specific to ATMega328P
.dseg
.org    SRAM_START

KEY_LAST: .byte 1      ; estado anterior de botones (para flanco)

CH_HOR_D: .byte 1
CH_HOR_U: .byte 1
CH_MIN_D: .byte 1
CH_MIN_U: .byte 1

CF_DIA_D: .byte 1
CF_DIA_U: .byte 1
CF_MES_D: .byte 1
CF_MES_U: .byte 1

DIA_U: .byte 1
DIA_D: .byte 1
MES_U: .byte 1
MES_D: .byte 1

A_MIN_U: .byte 1
A_MIN_D: .byte 1
A_HOR_U: .byte 1
A_HOR_D: .byte 1

PREV_MODE: .byte 1

.cseg

.equ T1VALUE = 0xC2F7		//49,911 PARA 1s
.equ M_HORA = 0
.equ M_FECHA = 1
.equ M_CONF_HORA = 2
.equ M_CONF_FECHA = 3
.equ M_CONF_ALARMA = 4
.equ BTN_SAVE_BIT = 3   ; PC3
.equ BTN_A_BIT    = 4   ; PC4
.equ BTN_B_BIT    = 5   ; PC5

.equ BTN_MASK     = (1<<PC3)|(1<<PC4)|(1<<PC5)

.equ EV_1S       = 0    ; tick de 1 segundo (solo si NO estás en config)
.equ EV_SAVE     = 1    ; botón PC3
.equ EV_INC_A    = 2    ; botón PC4
.equ EV_INC_B    = 3    ; botón PC5
					    
.equ ALARM_EN	 = 5    ; alarma habilitada
.equ ALARM_RING  = 6	; alarma sonando

.def TICKS = R18
.def SEG = R20
.def MIN_U = R21
.def MIN_D = R22
.def HOR_U = R23
.def HOR_D = R24
.def DIGIDX = R25
.def DIGITO	= R26
.def SALIDA7 = R27
.def FLAGS = R28		//bit 0 (1 - alarma activa, 0 - inactiva), bit1 si esta seteada o no
.def MODE = R19
.def MAXD = R12

.org 0x0000
	RJMP	SETUP
.org OVF0addr		//0x0020
	RJMP TIMER0_OVF
.org PCI1addr
	RJMP PORTC_ISR
.org	0x0040
	
 /****************************************/
// Configuración de la pila
SETUP:

segdig: .dB 0x40, 0x79, 0x24, 0x30, 0x19, 0x12, 0x02, 0x78, 0x00, 0x18
MAX_DIAS: .dB 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31

LDI     R16, LOW(RAMEND)
OUT     SPL, R16
LDI     R16, HIGH(RAMEND)
OUT     SPH, R16
/****************************************/
// Configuracion MCU

LDI		R16, (1 << CLKPCE)
STS		CLKPR, R16
LDI		R16, 0x04
STS		CLKPR, R16

LDI		R16, 0xFF
OUT		DDRD, R16			;DISPLAYS de 7 segmentos
LDI		R16, 0x00
OUT		PORTD, R16

LDI		R16, 0xFF
OUT		DDRB, R16			//PB0-PB3 multiplex y PB4 BUZZER
LDI		R16, 0x00
OUT		PORTB, R16

LDI		R16, 0x07
OUT		DDRC, R16
LDI		R16, 0x38	// pullups
OUT		PORTC, R16	

LDI		R16, (1 << PCIE1)
STS		PCICR, R16

LDI		R16, (1 << PCINT13) | (1 << PCINT12) | (1 << PCINT11)
STS		PCMSK1, R16

CLR		SEG
CLR		TICKS
CLR		MIN_U
CLR		MIN_D
CLR		HOR_U
CLR		HOR_D	
CLR		DIGIDX
CLR		DIGITO
CLR		SALIDA7
CLR		MODE
CLR		R0
CLR		FLAGS
CLR		MAXD

LDI		R16, 0x00
STS		A_MIN_U, R16
STS		A_MIN_D, R16
STS		A_HOR_U, R16
STS		A_HOR_D, R16

// PREV_MODE = M_HORA para empezar
LDI		R16, M_HORA
STS		PREV_MODE, R16

CBI		PORTB, PORTB4			;apagamos el buzzer inicialmente
SBI		PORTC, PORTC0			;el LED de hora empieza encendido

LDI R16, 0
STS DIA_U, R16
STS DIA_D, R16
STS MES_U, R16
STS MES_D, R16

LDI		R16, BTN_MASK
STS		KEY_LAST, R16

CALL INIT_TMR0

LDI		R16, (1 << TOIE0)
STS		TIMSK0, R16

SEI

    
/****************************************/
// Loop Infinito
MAIN_LOOP:
	SBRS	FLAGS, EV_SAVE
	RJMP    CHECK_PC4
	CBR		FLAGS, (1 << EV_SAVE)		//limpiamos la bandera

	CPI		MODE, M_CONF_HORA
	BRNE	SAVE_FECHA
	CALL	GUARDAR_HORA
	LDI		MODE, M_HORA
	RJMP	CHECK_1S

	SAVE_FECHA:
	CPI     MODE, M_CONF_FECHA
    BRNE    SAVE_ALARMA
    CALL    GUARDAR_FECHA
    LDI     MODE, M_FECHA
    RJMP    CHECK_1S

	SAVE_ALARMA:
	CPI		MODE, M_CONF_ALARMA
	BRNE	SAVE_NORMAL

	SBR		FLAGS, (1 << ALARM_EN)
	CBR		FLAGS, (1 << ALARM_RING)
	CBI		PORTB, PORTB4
	LDI		MODE, M_HORA
	RJMP	CHECK_1S

	/*LDS		R16, PREV_MODE
	MOV		MODE, R16
	RJMP	CHECK_1S*/

	SAVE_NORMAL:

	CPI		MODE, M_HORA
	BREQ	TO_FECHA
	CPI		MODE, M_FECHA
	BREQ	TO_HORA
	RJMP	CHECK_1S

	TO_FECHA:
	LDI		MODE, M_FECHA
	SBI		PORTC, PORTC1
	CBI		PORTC, PORTC0
	CBI		PORTC, PORTC2
	RJMP	CHECK_1S

	TO_HORA:
	LDI		MODE, M_HORA
	SBI		PORTC, PORTC0
	CBI		PORTC, PORTC1
	CBI		PORTC, PORTC2

	CHECK_PC4:
	SBRS	FLAGS, EV_INC_A
	RJMP	CHECK_PC5
	CBR		FLAGS, (1 << EV_INC_A)
	
	CPI		MODE, M_HORA	//si estoy en hora, entramos a conf hora
	BREQ	ENTER_CONF
	CPI		MODE, M_CONF_HORA
	BREQ	INC_MIN			//si estamos ya en conf, ahora incrementamos minutos

	CPI		MODE, M_FECHA
	BREQ	ENTER_CONF_FECHA_LBL

	CPI		MODE, M_CONF_FECHA
	BREQ	INC_MES

	CPI		MODE, M_CONF_ALARMA
	BREQ	INC_A_MIN_LBL

	RJMP	CHECK_PC5

	ENTER_CONF:
	CALL	ENTER_CONF_HORA			//copiamos la hora actual
	LDI		MODE, M_CONF_HORA
	CBR		FLAGS, (1 << EV_1S)
	RJMP	CHECK_1S

	INC_MIN:
	CALL	INC_CH_MIN
	RJMP	CHECK_1S

	ENTER_CONF_FECHA_LBL:
	CALL	ENTER_CONF_FECHA
	LDI		MODE, M_CONF_FECHA
	CBR		FLAGS, (1 << EV_1S)
	RJMP	CHECK_1S

	INC_MES:
	CALL	INC_CF_MES
	RJMP	CHECK_1S

	INC_A_MIN_LBL:
	CALL	INC_ALARM_MIN
	RJMP	CHECK_1S

	CHECK_PC5:
	SBRS	FLAGS, EV_INC_B
	RJMP	CHECK_1S
	CBR		FLAGS, (1 << EV_INC_B)

	CPI		MODE, M_HORA
	BREQ	ENTER_ALARMA
	CPI		MODE, M_FECHA
	BREQ	ENTER_ALARMA

	CPI		MODE, M_CONF_HORA
	BREQ	INC_HORA

	CPI		MODE, M_CONF_FECHA
	BREQ	INC_DIA

	CPI		MODE, M_CONF_ALARMA
	BREQ	INC_A_HOR_LBL

	RJMP	CHECK_1S

	ENTER_ALARMA:
	CALL	ENTER_CONF_ALARMA
	RJMP	CHECK_1S

	INC_A_HOR_LBL:
	CALL	INC_ALARM_HOR
	RJMP	CHECK_1S

	INC_HORA:
	CALL	INC_CH_HOR
	RJMP	CHECK_1S

	INC_DIA:
	CALL	INC_CF_DIA
	RJMP	CHECK_1S

	CHECK_1S:
	SBRS	FLAGS, EV_1S
	RJMP	MAIN_LOOP

	CBR		FLAGS, (1 << EV_1S)
	CALL	TICK_1S
	CALL	CHECK_ALARMA
	RJMP	MAIN_LOOP

/****************************************/
// NON-Interrupt subroutines

INIT_TMR0:		;usamos prescaler de 64, esto sera para el multiplexado
	LDI		R16, (1 << CS01) | (1 << CS00)
	OUT		TCCR0B, R16

	LDI		R16, 178		//aprox 5ms
	OUT		TCNT0, R16

	RET

TICK_1S:
	SBI		PINB, PINB5

	INC		SEG
	CPI		SEG, 60
	BRNE	TICK_END
	CLR		SEG

	//minutos
	INC		MIN_U
	CPI		MIN_U, 10
	BRNE	TICK_END
	CLR		MIN_U
	INC		MIN_D
	CPI		MIN_D, 6
	BRNE	TICK_END
	CLR		MIN_D

	//horas
	INC		HOR_U
	CPI		HOR_U, 10
	BRNE	FIX_24
	CLR		HOR_U
	INC		HOR_D

	FIX_24:
	CPI		HOR_D, 2
	BRNE	TICK_END
	CPI		HOR_U, 4
	BRNE	TICK_END
	CLR		HOR_D
	CLR		HOR_U
	
	CALL	INC_FECHA_REAL			//al llegar a 23 59, actualizamos el dia

	TICK_END:
	RET

ENTER_CONF_HORA:
	SBI		PORTC, PORTC0
	CBI		PORTC, PORTC1
	SBI		PORTC, PORTC2
	CBI		PORTB, PORTB5
	STS		CH_HOR_D, HOR_D
	STS		CH_HOR_U, HOR_U
	STS		CH_MIN_D, MIN_D
	STS		CH_MIN_U, MIN_U
	
	RET

GUARDAR_HORA:
	LDS		HOR_D, CH_HOR_D
	LDS		HOR_U, CH_HOR_U
	LDS		MIN_D, CH_MIN_D
	LDS		MIN_U, CH_MIN_U

	CLR		SEG
	CBI		PORTC, PORTC1
	SBI		PORTC, PORTC0
	CBI		PORTC, PORTC2

	RET

INC_CH_MIN:
	LDS		R16, CH_MIN_U
	INC		R16
	CPI		R16, 10
	BRNE	SAVE_CH_MIN_U
	CLR		R16
	STS		CH_MIN_U, R16

	LDS		R16, CH_MIN_D
	INC		R16
	CPI		R16, 6
	BRNE	SAVE_CH_MIN_D
	CLR		R16

	SAVE_CH_MIN_D:
	STS		CH_MIN_D, R16
	RET

	SAVE_CH_MIN_U:
	STS		CH_MIN_U, R16
	RET		//puedo tener 2 RETs?

INC_CH_HOR:
	LDS		R16, CH_HOR_U
	LDS		R17, CH_HOR_D
	INC		R16

	CPI		R17, 2
	BRNE	CONT_H
	CPI		R16, 4
	BRNE	CONT_H
	CLR		R16
	CLR		R17
	STS     CH_HOR_U, R16
    STS     CH_HOR_D, R17
    RET		

	CONT_H:
	CPI		R16, 10
	BRNE	SAVE_H
	CLR		R16
	INC		R17

	SAVE_H:
	STS		CH_HOR_U, R16
	STS		CH_HOR_D, R17
	
	RET

ENTER_CONF_FECHA:
	SBI		PORTC, PORTC1
	CBI		PORTC, PORTC0
	SBI		PORTC, PORTC2
	LDS		R16, DIA_U
	STS		CF_DIA_U, R16
	LDS		R16, DIA_D
	STS		CF_DIA_D, R16
	LDS		R16, MES_U
	STS		CF_MES_U, R16
	LDS		R16, MES_D
	STS		CF_MES_D, R16

	RET

GUARDAR_FECHA:
	LDS		R16, CF_DIA_U
	STS		DIA_U, R16
	LDS		R16, CF_DIA_D
	STS		DIA_D, R16
	LDS		R16, CF_MES_U
	STS		MES_U, R16
	LDS		R16, CF_MES_D
	STS		MES_D, R16

	SBI		PORTC, PORTC1
	CBI		PORTC, PORTC0
	CBI		PORTC, PORTC2

	RET

GET_MAX_DIA_CF:
	LDS		R16, CF_MES_D
	LDS		R17, CF_MES_U

	CPI		R16, 0
	BREQ	DECENAS0

	CPI		R16, 1
	BREQ	DECENAS1

	LDI		R16, 31
	MOV		MAXD, R16

	RET

	DECENAS0:
	DEC		R17
	RJMP	M_READ

	DECENAS1:
	LDI		R16, 9
	ADD		R17, R16

	M_READ:
	LDI		ZH, HIGH(MAX_DIAS << 1)
    LDI		ZL, LOW(MAX_DIAS << 1)
    ADD		ZL, R17
    ADC		ZH, R0
    LPM		MAXD, Z

	RET

INC_CF_DIA:
	CALL	GET_MAX_DIA_CF

	LDS		R16, CF_DIA_U
	LDS		R17, CF_DIA_D

	CPI		R17, 0
	BREQ	VAL_OK
	CPI		R17, 1
	BREQ	ADD10
	CPI		R17, 2
	BREQ	ADD20
	LDI		R30, 30
	ADD		R16, R30
	RJMP	VAL_OK

	ADD10:
	LDI		R30, 10
	ADD		R16, R30
	RJMP	VAL_OK

	ADD20:
	LDI		R30, 20
	ADD		R16, R30

	VAL_OK:
	INC		R16

	CP		MAXD, R16
	BRSH	CONVERT			//branch if same or higher 
	LDI		R16, 1

	CONVERT:
	CLR		R17

	DIV10_LOOP:
	CPI		R16, 10			
	BRLO	SAVE_DAY		//branch if lower
	SUBI	R16, 10			//subtract immediate
	INC		R17
	RJMP	DIV10_LOOP

	SAVE_DAY:
	STS		CF_DIA_D, R17
	STS		CF_DIA_U, R16

	RET

INC_CF_MES:
	LDS		R16, CF_MES_U
	LDS		R17, CF_MES_D

	INC		R16
	CPI		R16, 10
	BRNE	CHECK_13
	CLR		R16
	INC		R17

	CHECK_13:
	CPI		R17, 1
	BRNE	SAVE_M
	CPI		R16, 3
	BRNE	SAVE_M
	CLR		R17
	LDI		R16, 1

	SAVE_M:
	STS		CF_MES_D, R17
	STS		CF_MES_U, R16

	CALL	GET_MAX_DIA_CF

	LDS		R16, CF_DIA_U
	LDS		R17, CF_DIA_D

	CPI		R17, 0
	BREQ	DAY_BIN_OK
	CPI		R17, 1
	BREQ	DAY_ADD10
	CPI		R17, 2
	BREQ	DAY_ADD20
	LDI		R30, 30
	ADD		R16, R30
	RJMP	DAY_BIN_OK

	DAY_ADD10:
	LDI		R30, 10
	ADD		R16, R30
	RJMP	DAY_BIN_OK
	DAY_ADD20:
	LDI		R30, 20
	ADD		R16, R30

	DAY_BIN_OK:
	CP		MAXD, R16
	BRSH	DONE_MES

	MOV		R16, MAXD

	DIV10_M:
	CPI		R16, 10
	BRLO	SAVE_CLAMP
	SUBI	R16, 10
	INC		R17
	RJMP	DIV10_M

	SAVE_CLAMP:
	STS		CF_DIA_D, R17
	STS		CF_DIA_U, R16

	DONE_MES:
	RET

INC_FECHA_REAL:
	CALL	ENTER_CONF_FECHA			//guardamos la fecha real
	CALL	INC_CF_DIA

	LDS		R30, CF_DIA_D
	LDS		R31, CF_DIA_U
	CPI		R30, 0
	BRNE	NO_MONTH_INC
	CPI		R31, 1
	BRNE	NO_MONTH_INC

	CALL	INC_CF_MES

	NO_MONTH_INC:
	CALL	GUARDAR_FECHA
	
	RET

ENTER_CONF_ALARMA:
	SBI		PORTC, PORTC1
	SBI		PORTC, PORTC0
	SBI		PORTC, PORTC2
	STS		PREV_MODE, MODE
	LDI		MODE, M_CONF_ALARMA
	CBR		FLAGS, (1 << EV_1S)

	RET

INC_ALARM_MIN:
	LDS		R16, A_MIN_U
	INC		R16
	CPI		R16, 10
	BRNE	A_SAVE_MIN_U
	CLR		R16
	STS		A_MIN_U, R16

	LDS		R16, A_MIN_D
	INC		R16
	CPI		R16, 6
	BRNE	A_SAVE_MIN_D
	CLR		R16

	A_SAVE_MIN_D:
	STS		A_MIN_D, R16
	RET

	A_SAVE_MIN_U:
	STS		A_MIN_U, R16	
	RET

INC_ALARM_HOR:
	LDS		R16, A_HOR_U
	LDS		R17, A_HOR_D
	INC		R16

	CPI		R17, 2
	BRNE	A_CONT_H
	CPI		R16, 4
	BRNE	A_CONT_H
	CLR		R16
	CLR		R17
	STS     A_HOR_U, R16
    STS     A_HOR_D, R17
    RET		

	A_CONT_H:
	CPI		R16, 10
	BRNE	A_SAVE_H
	CLR		R16
	INC		R17

	A_SAVE_H:
	STS		A_HOR_U, R16
	STS		A_HOR_D, R17
	
	RET

CHECK_ALARMA:
	SBRS	FLAGS, ALARM_EN		;si alarma no enabled, hace ret
	RET

	SBRC	FLAGS, ALARM_RING	; si ya esta sonando, hace ret
	RET

	CPI		SEG, 0				; chequea solo al incio del segundo
	BRNE	CHECK_END

	LDS		R16, A_MIN_U
	CP		MIN_U, R16
	BRNE	CHECK_END
	LDS		R16, A_MIN_D
	CP		MIN_D, R16
	BRNE	CHECK_END

	LDS		R16, A_HOR_U
	CP		HOR_U, R16
	BRNE	CHECK_END
	LDS		R16, A_HOR_D
	CP		HOR_D, R16
	BRNE	CHECK_END

	SBR		FLAGS, (1 << ALARM_RING)
	SBI		PORTB, PORTB4

	CHECK_END:
	RET

/****************************************/
// Interrupt routines

TIMER0_OVF:
	PUSH	R16
	PUSH	R15
	PUSH	R17
	PUSH	R30
	PUSH	R31
	IN		R16, SREG
	PUSH	R16
	
	LDI		R16, 178		//aprox 5ms
	OUT		TCNT0, R16

	INC		TICKS
	CPI		TICKS, 200			// 200 * 5ms = 1s
	BRNE	DO_MUX
	CLR		TICKS

	CPI		MODE, M_CONF_HORA
	BREQ	DO_MUX
	CPI		MODE, M_CONF_FECHA
	BREQ	DO_MUX

	SBR		FLAGS, (1 << EV_1S)		//si no esta configurando, genera el segundo

	DO_MUX:

	CBI		PORTB, PORTB0
	CBI		PORTB, PORTB1
	CBI		PORTB, PORTB2
	CBI		PORTB, PORTB3

	CPI		MODE, M_HORA
	BREQ	SHOW_HORA
	CPI		MODE, M_FECHA
	BREQ	SHOW_FECHA

	CPI		MODE, M_CONF_HORA
	BREQ	SHOW_CONF_HORA
	CPI		MODE, M_CONF_FECHA
	BRNE	SKIP_SHOW_CONF_FECHA
	JMP		SHOW_CONF_FECHA
	SKIP_SHOW_CONF_FECHA:

	CPI		MODE, M_CONF_ALARMA
	BRNE	SKIP_ALARMA_SHOW
	JMP		SHOW_ALARMA
	SKIP_ALARMA_SHOW:

	SHOW_HORA:
	CPI		DIGIDX, 0
	BREQ	D0
	CPI		DIGIDX, 1
	BREQ	D1
	CPI		DIGIDX, 2
	BREQ	D2
	RJMP	D3		//tipo else

	D0:									//decimal hora
	MOV		DIGITO, HOR_D
	SBI		PORTB, PORTB0
	RJMP	SHOW

	D1:									//unidad hora
	MOV		DIGITO, HOR_U
	SBI		PORTB, PORTB1
	RJMP	SHOW

	D2:									//decimal minuto
	MOV		DIGITO, MIN_D
	SBI		PORTB, PORTB2
	RJMP	SHOW

	D3:									//unidad minuto
	MOV		DIGITO, MIN_U
	SBI		PORTB, PORTB3
	RJMP	SHOW

	SHOW_FECHA:
	CPI		DIGIDX, 0
	BREQ	F0
	CPI		DIGIDX, 1
	BREQ	F1
	CPI		DIGIDX, 2
	BREQ	F2
	RJMP	F3		//tipo else

	F0:									//decimal hora
	LDS		DIGITO, DIA_D
	SBI		PORTB, PORTB0
	RJMP	SHOW

	F1:									//unidad hora
	LDS		DIGITO, DIA_U
	SBI		PORTB, PORTB1
	RJMP	SHOW

	F2:									//decimal minuto
	LDS		DIGITO, MES_D
	SBI		PORTB, PORTB2
	RJMP	SHOW

	F3:									//unidad minuto
	LDS		DIGITO, MES_U
	SBI		PORTB, PORTB3
	RJMP	SHOW

	SHOW_CONF_HORA:
	CPI		DIGIDX, 0
	BREQ	CH0
	CPI		DIGIDX, 1
	BREQ	CH1
	CPI		DIGIDX, 2
	BREQ	CH2
	RJMP	CH3		//tipo else

	CH0:									//decimal hora
	LDS		DIGITO, CH_HOR_D
	SBI		PORTB, PORTB0
	RJMP	SHOW

	CH1:									//unidad hora
	LDS		DIGITO, CH_HOR_U
	SBI		PORTB, PORTB1
	RJMP	SHOW

	CH2:									//decimal minuto
	LDS		DIGITO, CH_MIN_D
	SBI		PORTB, PORTB2
	RJMP	SHOW

	CH3:									//unidad minuto
	LDS		DIGITO, CH_MIN_U
	SBI		PORTB, PORTB3
	RJMP	SHOW

	SHOW_CONF_FECHA:
	CPI		DIGIDX, 0
	BREQ	CF0
	CPI		DIGIDX, 1
	BREQ	CF1
	CPI		DIGIDX, 2
	BREQ	CF2
	RJMP	CF3		//tipo else

	CF0:									//decimal hora
	LDS		DIGITO, CF_DIA_D
	SBI		PORTB, PORTB0
	RJMP	SHOW

	CF1:									//unidad hora
	LDS		DIGITO, CF_DIA_U
	SBI		PORTB, PORTB1
	RJMP	SHOW

	CF2:									//decimal minuto
	LDS		DIGITO, CF_MES_D
	SBI		PORTB, PORTB2
	RJMP	SHOW

	CF3:									//unidad minuto
	LDS		DIGITO, CF_MES_U
	SBI		PORTB, PORTB3
	RJMP	SHOW

	SHOW_ALARMA:
	CPI		DIGIDX, 0
	BREQ	A0
	CPI		DIGIDX, 1
	BREQ	A1
	CPI		DIGIDX, 2
	BREQ	A2
	RJMP	A3		//tipo else

	A0:									//decimal hora
	LDS		DIGITO, A_HOR_D
	SBI		PORTB, PORTB0
	RJMP	SHOW

	A1:									//unidad hora
	LDS		DIGITO, A_HOR_U
	SBI		PORTB, PORTB1
	RJMP	SHOW

	A2:									//decimal minuto
	LDS		DIGITO, A_MIN_D
	SBI		PORTB, PORTB2
	RJMP	SHOW

	A3:									//unidad minuto
	LDS		DIGITO, A_MIN_U
	SBI		PORTB, PORTB3
	RJMP	SHOW

	SHOW:
	LDI		ZH, HIGH(segdig << 1)
    LDI		ZL, LOW(segdig << 1)
    ADD		ZL, DIGITO
    ADC		ZH, R0
    LPM		SALIDA7, Z
    OUT		PORTD, SALIDA7
	
	INC		DIGIDX
	CPI		DIGIDX, 4
	BRNE	SALIDA_ISR
	CLR		DIGIDX

	SALIDA_ISR:
	POP		R16
	OUT		SREG, R16
	POP		R31
	POP		R30
	POP		R17
	POP		R15
	POP		R16

	RETI

PORTC_ISR:
	PUSH	R16
	PUSH	R17
	PUSH	R15
	IN		R16, SREG
	PUSH	R16

	IN		R16, PINC
	ANDI	R16, BTN_MASK

	LDS		R17, KEY_LAST
	MOV		R15, R16
	COM		R15
	AND		R15, R17

	STS		KEY_LAST, R16

	// cualquier boton apaga la alarma y NO acciona el boton
	SBRS	FLAGS, ALARM_RING
	RJMP	CONT_EVENTS

	TST		R15							// es como decir AND	Rd, Rd
	BREQ	CONT_EVENTS

	CBR		FLAGS, (1 << ALARM_RING)
	CBI		PORTB, PORTB4
	RJMP	END_ISR


	// aqui si cuenta los eventos
	CONT_EVENTS:
	SBRS	R15, BTN_SAVE_BIT
	RJMP	CHECK_A
	SBR		FLAGS, (1 << EV_SAVE)

	CHECK_A:
	SBRS	R15, BTN_A_BIT
	RJMP	CHECK_B
	SBR		FLAGS, (1 << EV_INC_A)

	CHECK_B:
	SBRS	R15, BTN_B_BIT
	RJMP	END_ISR
	SBR		FLAGS, (1 << EV_INC_B)
	
	END_ISR:
	POP		R16
	OUT		SREG, R16
	POP		R15
	POP		R17
	POP		R16

	RETI



/****************************************/
